package amel;
// Generated May 12, 2019 1:48:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Naruceni generated by hbm2java
 */
@Entity
@Table(name="naruceni"
    ,catalog="bshop"
)
public class Naruceni  implements java.io.Serializable {


     private Integer idnaruceni;
     private String ime;
     private int mobitel;
     private int datum;
     private int vrijeme;

    public Naruceni() {
    }

    public Naruceni(String ime, int mobitel, int datum, int vrijeme) {
       this.ime = ime;
       this.mobitel = mobitel;
       this.datum = datum;
       this.vrijeme = vrijeme;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idnaruceni", unique=true, nullable=false)
    public Integer getIdnaruceni() {
        return this.idnaruceni;
    }
    
    public void setIdnaruceni(Integer idnaruceni) {
        this.idnaruceni = idnaruceni;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="mobitel", nullable=false)
    public int getMobitel() {
        return this.mobitel;
    }
    
    public void setMobitel(int mobitel) {
        this.mobitel = mobitel;
    }

    
    @Column(name="datum", nullable=false)
    public int getDatum() {
        return this.datum;
    }
    
    public void setDatum(int datum) {
        this.datum = datum;
    }

    
    @Column(name="vrijeme", nullable=false)
    public int getVrijeme() {
        return this.vrijeme;
    }
    
    public void setVrijeme(int vrijeme) {
        this.vrijeme = vrijeme;
    }




}


