/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amel;

import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author wedad
 */
public class P1 extends javax.swing.JFrame {

    
     public Session session = NewHibernateUtil.getSessionFactory().openSession();
    public Transaction tx = null;
    Naruceni n;
    
    /**
     * Creates new form P1
     */
    public P1() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p22 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        p1o5 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        p65 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        p66 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        p1o2 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        p32 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        p33 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        p23 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        p24 = new javax.swing.JLabel();
        p25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        p26 = new javax.swing.JLabel();
        p34 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        p35 = new javax.swing.JLabel();
        p36 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        p37 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        p38 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        p39 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        p40 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        p41 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        p42 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        p1o3 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p43 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        p44 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        p45 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        p46 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p47 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        p48 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        p49 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        p50 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        p51 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p1o = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p52 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        p53 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        p1o4 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        p54 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        p55 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        p56 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        p57 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        p58 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        p59 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        p16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        p17 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        p18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        p60 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        p61 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        p62 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        p63 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        p27 = new javax.swing.JLabel();
        p64 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        p28 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        p29 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        p19 = new javax.swing.JLabel();
        p30 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        p20 = new javax.swing.JLabel();
        p31 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        p1o1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        p21 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();

        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        p22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p22.setForeground(new java.awt.Color(255, 0, 102));
        p22.setText("Slobodno");

        jLabel46.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel46.setText("02.06.2019");

        jLabel99.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel99.setText("18:00 h");

        p1o5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o5.setForeground(new java.awt.Color(255, 0, 102));
        p1o5.setText("Slobodno");

        jLabel100.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel100.setText("19:00 h");

        p65.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p65.setForeground(new java.awt.Color(255, 0, 102));
        p65.setText("Slobodno");

        jLabel101.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel101.setText("20:00 h");

        p66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p66.setForeground(new java.awt.Color(255, 0, 102));
        p66.setText("Slobodno");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel57.setText("18:00 h");

        p1o2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o2.setForeground(new java.awt.Color(255, 0, 102));
        p1o2.setText("Slobodno");

        jLabel58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel58.setText("19:00 h");

        p32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p32.setForeground(new java.awt.Color(255, 0, 102));
        p32.setText("Slobodno");

        jLabel59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel59.setText("20:00 h");

        p33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p33.setForeground(new java.awt.Color(255, 0, 102));
        p33.setText("Slobodno");

        jLabel60.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel60.setText("03.06.2019");

        jLabel47.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel47.setText("Utorak");

        jLabel61.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel61.setText("Srijeda");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setText("09:00 h");

        jLabel62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel62.setText("09:00 h");

        p23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p23.setForeground(new java.awt.Color(255, 0, 102));
        p23.setText("Slobodno");

        jLabel49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel49.setText("10:00 h");

        p24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p24.setForeground(new java.awt.Color(255, 0, 102));
        p24.setText("Slobodno");

        p25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p25.setForeground(new java.awt.Color(255, 0, 102));
        p25.setText("Slobodno");

        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setText("11:00 h");

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setText("12:00 h");

        p26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p26.setForeground(new java.awt.Color(255, 0, 102));
        p26.setText("Slobodno");

        p34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p34.setForeground(new java.awt.Color(255, 0, 102));
        p34.setText("Slobodno");

        jLabel63.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel63.setText("10:00 h");

        p35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p35.setForeground(new java.awt.Color(255, 0, 102));
        p35.setText("Slobodno");

        p36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p36.setForeground(new java.awt.Color(255, 0, 102));
        p36.setText("Slobodno");

        jLabel64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel64.setText("11:00 h");

        jLabel65.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel65.setText("12:00 h");

        p37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p37.setForeground(new java.awt.Color(255, 0, 102));
        p37.setText("Slobodno");

        jLabel66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel66.setText("13:00 h");

        p38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p38.setForeground(new java.awt.Color(255, 0, 102));
        p38.setText("Slobodno");

        jLabel67.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel67.setText("14:00 h");

        p39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p39.setForeground(new java.awt.Color(255, 0, 102));
        p39.setText("Slobodno");

        jLabel68.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel68.setText("15:00 h");

        p40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p40.setForeground(new java.awt.Color(255, 0, 102));
        p40.setText("Slobodno");

        jLabel69.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel69.setText("16:00 h");

        p41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p41.setForeground(new java.awt.Color(255, 0, 102));
        p41.setText("Slobodno");

        jLabel70.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel70.setText("17:00 h");

        p42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p42.setForeground(new java.awt.Color(255, 0, 102));
        p42.setText("Slobodno");

        jLabel71.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel71.setText("18:00 h");

        p1o3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o3.setForeground(new java.awt.Color(255, 0, 102));
        p1o3.setText("Slobodno");

        jLabel72.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel72.setText("19:00 h");

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel10.setText("Ponedjeljak");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("09:00 h");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("10:00 h");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("11:00 h");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("12:00 h");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("13:00 h");

        p43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p43.setForeground(new java.awt.Color(255, 0, 102));
        p43.setText("Slobodno");

        jLabel73.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel73.setText("20:00 h");

        p44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p44.setForeground(new java.awt.Color(255, 0, 102));
        p44.setText("Slobodno");

        jLabel74.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel74.setText("Petak");

        jLabel75.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel75.setText("05.06.2019");

        jLabel76.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel76.setText("09:00 h");

        p45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p45.setForeground(new java.awt.Color(255, 0, 102));
        p45.setText("Slobodno");

        jLabel77.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel77.setText("10:00 h");

        p46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p46.setForeground(new java.awt.Color(255, 0, 102));
        p46.setText("Slobodno");

        jLabel78.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel78.setText("11:00 h");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("14:00 h");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("15:00 h");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("16:00 h");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("17:00 h");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("18:00 h");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("19:00 h");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("20:00 h");

        p1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 0, 102));
        p1.setText("Slobodno");

        p2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 0, 102));
        p2.setText("Slobodno");

        p3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 0, 102));
        p3.setText("Slobodno");

        p47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p47.setForeground(new java.awt.Color(255, 0, 102));
        p47.setText("Slobodno");

        jLabel79.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel79.setText("12:00 h");

        p48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p48.setForeground(new java.awt.Color(255, 0, 102));
        p48.setText("Slobodno");

        jLabel80.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel80.setText("13:00 h");

        p49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p49.setForeground(new java.awt.Color(255, 0, 102));
        p49.setText("Slobodno");

        jLabel81.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel81.setText("14:00 h");

        p50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p50.setForeground(new java.awt.Color(255, 0, 102));
        p50.setText("Slobodno");

        jLabel82.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel82.setText("15:00 h");

        p51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p51.setForeground(new java.awt.Color(255, 0, 102));
        p51.setText("Slobodno");

        jLabel83.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel83.setText("16:00 h");

        p4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 0, 102));
        p4.setText("Slobodno");

        p5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 0, 102));
        p5.setText("Slobodno");

        p6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 0, 102));
        p6.setText("Slobodno");

        p7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 0, 102));
        p7.setText("Slobodno");

        p8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 0, 102));
        p8.setText("Slobodno");

        p9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 0, 102));
        p9.setText("Slobodno");

        p1o.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o.setForeground(new java.awt.Color(255, 0, 102));
        p1o.setText("Slobodno");

        p11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 0, 102));
        p11.setText("Slobodno");

        p12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p12.setForeground(new java.awt.Color(255, 0, 102));
        p12.setText("Slobodno");

        p52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p52.setForeground(new java.awt.Color(255, 0, 102));
        p52.setText("Slobodno");

        jLabel84.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel84.setText("17:00 h");

        p53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p53.setForeground(new java.awt.Color(255, 0, 102));
        p53.setText("Slobodno");

        jLabel85.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel85.setText("18:00 h");

        p1o4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o4.setForeground(new java.awt.Color(255, 0, 102));
        p1o4.setText("Slobodno");

        jLabel86.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel86.setText("19:00 h");

        p54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p54.setForeground(new java.awt.Color(255, 0, 102));
        p54.setText("Slobodno");

        jLabel87.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel87.setText("20:00 h");

        p55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p55.setForeground(new java.awt.Color(255, 0, 102));
        p55.setText("Slobodno");

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("01.06.2019");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("04.06.2019");

        jLabel33.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel33.setText("Cetvrtak");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setText("09:00 h");

        p10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 0, 102));
        p10.setText("Slobodno");

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setText("10:00 h");

        p13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p13.setForeground(new java.awt.Color(255, 0, 102));
        p13.setText("Slobodno");

        p14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p14.setForeground(new java.awt.Color(255, 0, 102));
        p14.setText("Slobodno");

        jLabel88.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel88.setText("Subota");

        jLabel89.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel89.setText("06.06.2019");

        jLabel90.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel90.setText("09:00 h");

        p56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p56.setForeground(new java.awt.Color(255, 0, 102));
        p56.setText("Slobodno");

        jLabel91.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel91.setText("10:00 h");

        p57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p57.setForeground(new java.awt.Color(255, 0, 102));
        p57.setText("Slobodno");

        jLabel92.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel92.setText("11:00 h");

        p58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p58.setForeground(new java.awt.Color(255, 0, 102));
        p58.setText("Slobodno");

        jLabel93.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel93.setText("12:00 h");

        p59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p59.setForeground(new java.awt.Color(255, 0, 102));
        p59.setText("Slobodno");

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setText("11:00 h");

        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setText("12:00 h");

        p15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p15.setForeground(new java.awt.Color(255, 0, 102));
        p15.setText("Slobodno");

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setText("13:00 h");

        p16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p16.setForeground(new java.awt.Color(255, 0, 102));
        p16.setText("Slobodno");

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setText("14:00 h");

        p17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p17.setForeground(new java.awt.Color(255, 0, 102));
        p17.setText("Slobodno");

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setText("15:00 h");

        p18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p18.setForeground(new java.awt.Color(255, 0, 102));
        p18.setText("Slobodno");

        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setText("16:00 h");

        jLabel94.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel94.setText("13:00 h");

        p60.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p60.setForeground(new java.awt.Color(255, 0, 102));
        p60.setText("Slobodno");

        jLabel95.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel95.setText("14:00 h");

        p61.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p61.setForeground(new java.awt.Color(255, 0, 102));
        p61.setText("Slobodno");

        jLabel96.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel96.setText("15:00 h");

        p62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p62.setForeground(new java.awt.Color(255, 0, 102));
        p62.setText("Slobodno");

        jLabel97.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel97.setText("16:00 h");

        p63.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p63.setForeground(new java.awt.Color(255, 0, 102));
        p63.setText("Slobodno");

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setText("13:00 h");

        jLabel98.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel98.setText("17:00 h");

        p27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p27.setForeground(new java.awt.Color(255, 0, 102));
        p27.setText("Slobodno");

        p64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p64.setForeground(new java.awt.Color(255, 0, 102));
        p64.setText("Slobodno");

        jLabel53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel53.setText("14:00 h");

        p28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p28.setForeground(new java.awt.Color(255, 0, 102));
        p28.setText("Slobodno");

        jLabel54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel54.setText("15:00 h");

        p29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p29.setForeground(new java.awt.Color(255, 0, 102));
        p29.setText("Slobodno");

        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setText("16:00 h");

        p19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p19.setForeground(new java.awt.Color(255, 0, 102));
        p19.setText("Slobodno");

        p30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p30.setForeground(new java.awt.Color(255, 0, 102));
        p30.setText("Slobodno");

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setText("17:00 h");

        jLabel56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel56.setText("17:00 h");

        p20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p20.setForeground(new java.awt.Color(255, 0, 102));
        p20.setText("Slobodno");

        p31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p31.setForeground(new java.awt.Color(255, 0, 102));
        p31.setText("Slobodno");

        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setText("18:00 h");

        p1o1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o1.setForeground(new java.awt.Color(255, 0, 102));
        p1o1.setText("Slobodno");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setText("19:00 h");

        p21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p21.setForeground(new java.awt.Color(255, 0, 102));
        p21.setText("Slobodno");

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setText("20:00 h");

        jToggleButton8.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton8.setText("Sljedeca");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton7.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton7.setText("Osvjezi");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel47)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel61)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel33)
                        .addGap(194, 194, 194)
                        .addComponent(jLabel74)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel88))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11)
                        .addGap(17, 17, 17)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel48)
                        .addGap(17, 17, 17)
                        .addComponent(p23, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel62)
                        .addGap(17, 17, 17)
                        .addComponent(p34, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel34)
                        .addGap(17, 17, 17)
                        .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel76)
                        .addGap(17, 17, 17)
                        .addComponent(p45, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel90)
                        .addGap(17, 17, 17)
                        .addComponent(p56, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(p24, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel63)
                        .addGap(18, 18, 18)
                        .addComponent(p35, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel77)
                        .addGap(18, 18, 18)
                        .addComponent(p46, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel91)
                        .addGap(18, 18, 18)
                        .addComponent(p57, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(p25, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel64)
                        .addGap(18, 18, 18)
                        .addComponent(p36, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel78)
                        .addGap(18, 18, 18)
                        .addComponent(p47, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel92)
                        .addGap(18, 18, 18)
                        .addComponent(p58, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel51)
                        .addGap(18, 18, 18)
                        .addComponent(p26, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel65)
                        .addGap(18, 18, 18)
                        .addComponent(p37, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel79)
                        .addGap(18, 18, 18)
                        .addComponent(p48, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel93)
                        .addGap(18, 18, 18)
                        .addComponent(p59, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(p27, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel66)
                        .addGap(18, 18, 18)
                        .addComponent(p38, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(p16, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel80)
                        .addGap(18, 18, 18)
                        .addComponent(p49, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel94)
                        .addGap(18, 18, 18)
                        .addComponent(p60, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel53)
                        .addGap(18, 18, 18)
                        .addComponent(p28, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel67)
                        .addGap(18, 18, 18)
                        .addComponent(p39, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(p17, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel81)
                        .addGap(18, 18, 18)
                        .addComponent(p50, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel95)
                        .addGap(18, 18, 18)
                        .addComponent(p61, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel54)
                        .addGap(18, 18, 18)
                        .addComponent(p29, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel68)
                        .addGap(18, 18, 18)
                        .addComponent(p40, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(p18, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel82)
                        .addGap(18, 18, 18)
                        .addComponent(p51, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel96)
                        .addGap(18, 18, 18)
                        .addComponent(p62, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel55)
                        .addGap(18, 18, 18)
                        .addComponent(p30, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel69)
                        .addGap(18, 18, 18)
                        .addComponent(p41, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(p19, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel83)
                        .addGap(18, 18, 18)
                        .addComponent(p52, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel97)
                        .addGap(18, 18, 18)
                        .addComponent(p63, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel19)
                        .addGap(17, 17, 17)
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel56)
                        .addGap(17, 17, 17)
                        .addComponent(p31, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel70)
                        .addGap(17, 17, 17)
                        .addComponent(p42, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel42)
                        .addGap(17, 17, 17)
                        .addComponent(p20, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel84)
                        .addGap(17, 17, 17)
                        .addComponent(p53, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel98)
                        .addGap(17, 17, 17)
                        .addComponent(p64, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel20)
                        .addGap(17, 17, 17)
                        .addComponent(p1o, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel57)
                        .addGap(17, 17, 17)
                        .addComponent(p1o2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel71)
                        .addGap(17, 17, 17)
                        .addComponent(p1o3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel43)
                        .addGap(17, 17, 17)
                        .addComponent(p1o1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel85)
                        .addGap(17, 17, 17)
                        .addComponent(p1o4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel99)
                        .addGap(17, 17, 17)
                        .addComponent(p1o5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel21)
                        .addGap(17, 17, 17)
                        .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel58)
                        .addGap(12, 12, 12)
                        .addComponent(p32, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel72)
                        .addGap(17, 17, 17)
                        .addComponent(p43, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel44)
                        .addGap(17, 17, 17)
                        .addComponent(p21, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel86)
                        .addGap(17, 17, 17)
                        .addComponent(p54, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel100)
                        .addGap(17, 17, 17)
                        .addComponent(p65, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel22)
                        .addGap(17, 17, 17)
                        .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel59)
                        .addGap(17, 17, 17)
                        .addComponent(p33, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel73)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton7)
                                .addGap(84, 84, 84)
                                .addComponent(jToggleButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p44, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel45)
                                .addGap(17, 17, 17)
                                .addComponent(p22, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel87)
                                .addGap(17, 17, 17)
                                .addComponent(p55, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel101)
                                .addGap(17, 17, 17)
                                .addComponent(p66, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel31))
                    .addComponent(jLabel46)
                    .addComponent(jLabel60)
                    .addComponent(jLabel32)
                    .addComponent(jLabel75)
                    .addComponent(jLabel89))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addComponent(jLabel47)
                    .addComponent(jLabel61)
                    .addComponent(jLabel33)
                    .addComponent(jLabel74)
                    .addComponent(jLabel88))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(p1)
                    .addComponent(jLabel48)
                    .addComponent(p23)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addComponent(p34)
                            .addComponent(jLabel34)
                            .addComponent(p10)
                            .addComponent(jLabel76)
                            .addComponent(p45)
                            .addComponent(jLabel90)
                            .addComponent(p56))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(p2)
                    .addComponent(jLabel49)
                    .addComponent(p24)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(p35)
                            .addComponent(jLabel35)
                            .addComponent(p13)
                            .addComponent(jLabel77)
                            .addComponent(p46)
                            .addComponent(jLabel91)
                            .addComponent(p57))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(p3)
                    .addComponent(jLabel50)
                    .addComponent(p25)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64)
                            .addComponent(p36)
                            .addComponent(jLabel36)
                            .addComponent(p14)
                            .addComponent(jLabel78)
                            .addComponent(p47)
                            .addComponent(jLabel92)
                            .addComponent(p58))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(p4)
                    .addComponent(jLabel51)
                    .addComponent(p26)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addComponent(p37)
                            .addComponent(jLabel37)
                            .addComponent(p15)
                            .addComponent(jLabel79)
                            .addComponent(p48)
                            .addComponent(jLabel93)
                            .addComponent(p59))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(p5)
                    .addComponent(jLabel52)
                    .addComponent(p27)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(p38)
                            .addComponent(jLabel38)
                            .addComponent(p16)
                            .addComponent(jLabel80)
                            .addComponent(p49)
                            .addComponent(jLabel94)
                            .addComponent(p60))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(p6)
                    .addComponent(jLabel53)
                    .addComponent(p28)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel67)
                            .addComponent(p39)
                            .addComponent(jLabel39)
                            .addComponent(p17)
                            .addComponent(jLabel81)
                            .addComponent(p50)
                            .addComponent(jLabel95)
                            .addComponent(p61))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(p7)
                    .addComponent(jLabel54)
                    .addComponent(p29)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(p40)
                            .addComponent(jLabel40)
                            .addComponent(p18)
                            .addComponent(jLabel82)
                            .addComponent(p51)
                            .addComponent(jLabel96)
                            .addComponent(p62))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(p8)
                    .addComponent(jLabel55)
                    .addComponent(p30)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(p41)
                            .addComponent(jLabel41)
                            .addComponent(p19)
                            .addComponent(jLabel83)
                            .addComponent(p52)
                            .addComponent(jLabel97)
                            .addComponent(p63))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(p9)
                    .addComponent(jLabel56)
                    .addComponent(p31)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(p42)
                            .addComponent(jLabel42)
                            .addComponent(p20)
                            .addComponent(jLabel84)
                            .addComponent(p53)
                            .addComponent(jLabel98)
                            .addComponent(p64))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(p1o)
                    .addComponent(jLabel57)
                    .addComponent(p1o2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addComponent(p1o3)
                            .addComponent(jLabel43)
                            .addComponent(p1o1)
                            .addComponent(jLabel85)
                            .addComponent(p1o4)
                            .addComponent(jLabel99)
                            .addComponent(p1o5))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(p11)
                    .addComponent(jLabel58)
                    .addComponent(p32)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72)
                            .addComponent(p43)
                            .addComponent(jLabel44)
                            .addComponent(p21)
                            .addComponent(jLabel86)
                            .addComponent(p54)
                            .addComponent(jLabel100)
                            .addComponent(p65))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(p12)
                    .addComponent(jLabel59)
                    .addComponent(p33)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addComponent(p44)
                            .addComponent(jLabel45)
                            .addComponent(p22)
                            .addComponent(jLabel87)
                            .addComponent(p55)
                            .addComponent(jLabel101)
                            .addComponent(p66))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
      
         new P1().dispose();
        new P2().setVisible(true);
     
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
 String hql = "select zap from Naruceni zap where zap.vrijeme = '" + 9 + "'" + "and zap.datum ='" + 1062019 + "'";
        Query query = session.createQuery(hql);
        List<Naruceni> zap = null;

        try {

            tx = session.beginTransaction();

            zap = query.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat = new StringBuilder();

        for (Naruceni person1 : zap) {

            rezultat.append(person1.getIme());
            rezultat.append(" ");
            rezultat.append(person1.getMobitel());

            p1.setText(rezultat.toString());
        }

        String hq2 = "select zap from Naruceni zap where zap.vrijeme = '" + 10 + "'" + "and zap.datum ='" +  1062019 + "'";
        Query query1 = session.createQuery(hq2);
        List<Naruceni> zap1 = null;

        try {

            tx = session.beginTransaction();

            zap1 = query1.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat2 = new StringBuilder();

        for (Naruceni person2 : zap1) {

            rezultat2.append(person2.getIme());
            rezultat2.append(" ");
            rezultat2.append(person2.getMobitel());

            p2.setText(rezultat2.toString());
        }
         String hq3 = "select zap from Naruceni zap where zap.vrijeme = '" + 11 + "'" + "and zap.datum ='" +  1062019 + "'";
        Query query3 = session.createQuery(hq3);
        List<Naruceni> zap3 = null;

        try {

            tx = session.beginTransaction();

            zap3 = query3.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat3 = new StringBuilder();

        for (Naruceni person3 : zap3) {

            rezultat3.append(person3.getIme());
            rezultat3.append(" ");
            rezultat3.append(person3.getMobitel());

            p3.setText(rezultat3.toString());
        }
         String hq4 = "select zap from Naruceni zap where zap.vrijeme = '" + 12 + "'" + "and zap.datum ='" +  1062019 + "'";
        Query query4 = session.createQuery(hq4);
        List<Naruceni> zap4 = null;

        try {

            tx = session.beginTransaction();

            zap4= query4.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat4 = new StringBuilder();

        for (Naruceni person4 : zap4) {

            rezultat4.append(person4.getIme());
            rezultat4.append(" ");
            rezultat4.append(person4.getMobitel());

            p4.setText(rezultat4.toString());
        }
         String hq5 = "select zap from Naruceni zap where zap.vrijeme = '" + 13 + "'" + "and zap.datum ='" +  1062019 + "'";
        Query query5 = session.createQuery(hq5);
        List<Naruceni> zap5 = null;

        try {

            tx = session.beginTransaction();

            zap5= query5.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat5 = new StringBuilder();

        for (Naruceni person5 : zap5) {

            rezultat5.append(person5.getIme());
            rezultat5.append(" ");
            rezultat5.append(person5.getMobitel());

            p5.setText(rezultat5.toString());
        }
         String hq6 = "select zap from Naruceni zap where zap.vrijeme = '" + 14 + "'" + "and zap.datum ='" +  1062019 + "'";
        Query query6 = session.createQuery(hq6);
        List<Naruceni> zap6 = null;

        try {

            tx = session.beginTransaction();

            zap6= query6.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }

        StringBuilder rezultat6 = new StringBuilder();

        for (Naruceni person6 : zap6) {

            rezultat6.append(person6.getIme());
            rezultat6.append(" ");
            rezultat6.append(person6.getMobitel());

            p6.setText(rezultat6.toString());
        }
       
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p14;
    private javax.swing.JLabel p15;
    private javax.swing.JLabel p16;
    private javax.swing.JLabel p17;
    private javax.swing.JLabel p18;
    private javax.swing.JLabel p19;
    private javax.swing.JLabel p1o;
    private javax.swing.JLabel p1o1;
    private javax.swing.JLabel p1o2;
    private javax.swing.JLabel p1o3;
    private javax.swing.JLabel p1o4;
    private javax.swing.JLabel p1o5;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p20;
    private javax.swing.JLabel p21;
    private javax.swing.JLabel p22;
    private javax.swing.JLabel p23;
    private javax.swing.JLabel p24;
    private javax.swing.JLabel p25;
    private javax.swing.JLabel p26;
    private javax.swing.JLabel p27;
    private javax.swing.JLabel p28;
    private javax.swing.JLabel p29;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p30;
    private javax.swing.JLabel p31;
    private javax.swing.JLabel p32;
    private javax.swing.JLabel p33;
    private javax.swing.JLabel p34;
    private javax.swing.JLabel p35;
    private javax.swing.JLabel p36;
    private javax.swing.JLabel p37;
    private javax.swing.JLabel p38;
    private javax.swing.JLabel p39;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p40;
    private javax.swing.JLabel p41;
    private javax.swing.JLabel p42;
    private javax.swing.JLabel p43;
    private javax.swing.JLabel p44;
    private javax.swing.JLabel p45;
    private javax.swing.JLabel p46;
    private javax.swing.JLabel p47;
    private javax.swing.JLabel p48;
    private javax.swing.JLabel p49;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p50;
    private javax.swing.JLabel p51;
    private javax.swing.JLabel p52;
    private javax.swing.JLabel p53;
    private javax.swing.JLabel p54;
    private javax.swing.JLabel p55;
    private javax.swing.JLabel p56;
    private javax.swing.JLabel p57;
    private javax.swing.JLabel p58;
    private javax.swing.JLabel p59;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p60;
    private javax.swing.JLabel p61;
    private javax.swing.JLabel p62;
    private javax.swing.JLabel p63;
    private javax.swing.JLabel p64;
    private javax.swing.JLabel p65;
    private javax.swing.JLabel p66;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
}
