/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amel;

/**
 *
 * @author wedad
 */
public class P2 extends javax.swing.JFrame {

    /**
     * Creates new form P2
     */
    public P2() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p14 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p56 = new javax.swing.JLabel();
        p1o = new javax.swing.JLabel();
        p11 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p52 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        p53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        p1o2 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        p32 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        p33 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        p57 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        p22 = new javax.swing.JLabel();
        p58 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        p59 = new javax.swing.JLabel();
        p1o5 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        p65 = new javax.swing.JLabel();
        p15 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        p66 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        p23 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        p24 = new javax.swing.JLabel();
        p25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        p16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        p17 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        p18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        p60 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        p61 = new javax.swing.JLabel();
        p26 = new javax.swing.JLabel();
        p34 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        p35 = new javax.swing.JLabel();
        p36 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        p37 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        p38 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        p62 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        p63 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        p27 = new javax.swing.JLabel();
        p64 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        p28 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        p39 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        p40 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        p41 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        p42 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        p1o3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        p29 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        p19 = new javax.swing.JLabel();
        p30 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        p20 = new javax.swing.JLabel();
        p31 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        p43 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        p44 = new javax.swing.JLabel();
        p1o1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        p21 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        p45 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        p46 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p47 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        p48 = new javax.swing.JLabel();
        p1o4 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        p54 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        p55 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        p49 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        p50 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        p51 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p5.setForeground(new java.awt.Color(255, 0, 102));
        p5.setText("Slobodno");
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 219, -1));

        p6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p6.setForeground(new java.awt.Color(255, 0, 102));
        p6.setText("Slobodno");
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 219, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, 220, 17));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setText("09:00 h");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, -1, -1));

        p10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p10.setForeground(new java.awt.Color(255, 0, 102));
        p10.setText("Slobodno");
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, 219, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setText("10:00 h");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, -1, -1));

        p13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p13.setForeground(new java.awt.Color(255, 0, 102));
        p13.setText("Slobodno");
        getContentPane().add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 219, -1));

        p14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p14.setForeground(new java.awt.Color(255, 0, 102));
        p14.setText("Slobodno");
        getContentPane().add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 219, -1));

        jLabel88.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel88.setText("Subota");
        getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 70, -1, -1));

        p7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 0, 102));
        p7.setText("Slobodno");
        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 219, -1));

        jLabel89.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel89.setText("06.06.2019");
        getContentPane().add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 30, 120, -1));

        p8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p8.setForeground(new java.awt.Color(255, 0, 102));
        p8.setText("Slobodno");
        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 219, -1));

        jLabel90.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel90.setText("09:00 h");
        getContentPane().add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 180, -1, -1));

        p9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p9.setForeground(new java.awt.Color(255, 0, 102));
        p9.setText("Slobodno");
        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 219, -1));

        p56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p56.setForeground(new java.awt.Color(255, 0, 102));
        p56.setText("Slobodno");
        getContentPane().add(p56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 180, 219, -1));

        p1o.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o.setForeground(new java.awt.Color(255, 0, 102));
        p1o.setText("Slobodno");
        getContentPane().add(p1o, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, 219, -1));

        p11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p11.setForeground(new java.awt.Color(255, 0, 102));
        p11.setText("Slobodno");
        getContentPane().add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 790, 219, -1));

        p12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p12.setForeground(new java.awt.Color(255, 0, 102));
        p12.setText("Slobodno");
        getContentPane().add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 850, 219, -1));

        p52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p52.setForeground(new java.awt.Color(255, 0, 102));
        p52.setText("Slobodno");
        getContentPane().add(p52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 610, 219, -1));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel84.setText("17:00 h");
        getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 670, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 130, 220, 17));

        p53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p53.setForeground(new java.awt.Color(255, 0, 102));
        p53.setText("Slobodno");
        getContentPane().add(p53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 670, 219, -1));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel57.setText("18:00 h");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, -1, -1));

        jLabel85.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel85.setText("18:00 h");
        getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 730, -1, -1));

        p1o2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o2.setForeground(new java.awt.Color(255, 0, 102));
        p1o2.setText("Slobodno");
        getContentPane().add(p1o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 730, 219, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel58.setText("19:00 h");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 790, -1, -1));

        p32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p32.setForeground(new java.awt.Color(255, 0, 102));
        p32.setText("Slobodno");
        getContentPane().add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 790, 219, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel59.setText("20:00 h");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 850, -1, -1));

        p33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p33.setForeground(new java.awt.Color(255, 0, 102));
        p33.setText("Slobodno");
        getContentPane().add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 850, 219, -1));

        jLabel60.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel60.setText("03.06.2019");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 120, -1));

        jLabel47.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel47.setText("Utorak");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel61.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel61.setText("Srijeda");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jLabel91.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel91.setText("10:00 h");
        getContentPane().add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 240, -1, -1));

        p57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p57.setForeground(new java.awt.Color(255, 0, 102));
        p57.setText("Slobodno");
        getContentPane().add(p57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 240, 219, -1));

        jLabel92.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel92.setText("11:00 h");
        getContentPane().add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 300, -1, -1));

        p22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p22.setForeground(new java.awt.Color(255, 0, 102));
        p22.setText("Slobodno");
        getContentPane().add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 850, 219, -1));

        p58.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p58.setForeground(new java.awt.Color(255, 0, 102));
        p58.setText("Slobodno");
        getContentPane().add(p58, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 300, 219, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel46.setText("02.06.2019");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 120, -1));

        jLabel93.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel93.setText("12:00 h");
        getContentPane().add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 370, -1, -1));

        jLabel99.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel99.setText("18:00 h");
        getContentPane().add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 730, -1, -1));

        p59.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p59.setForeground(new java.awt.Color(255, 0, 102));
        p59.setText("Slobodno");
        getContentPane().add(p59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 370, 219, -1));

        p1o5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o5.setForeground(new java.awt.Color(255, 0, 102));
        p1o5.setText("Slobodno");
        getContentPane().add(p1o5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 730, 219, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setText("11:00 h");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, -1, -1));

        jLabel100.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel100.setText("19:00 h");
        getContentPane().add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 790, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setText("12:00 h");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, -1, -1));

        p65.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p65.setForeground(new java.awt.Color(255, 0, 102));
        p65.setText("Slobodno");
        getContentPane().add(p65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 790, 219, -1));

        p15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p15.setForeground(new java.awt.Color(255, 0, 102));
        p15.setText("Slobodno");
        getContentPane().add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 219, -1));

        jLabel101.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel101.setText("20:00 h");
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 850, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setText("13:00 h");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, -1, -1));

        p66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p66.setForeground(new java.awt.Color(255, 0, 102));
        p66.setText("Slobodno");
        getContentPane().add(p66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 850, 219, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 220, 13));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 220, 14));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setText("09:00 h");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel62.setText("09:00 h");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        p23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p23.setForeground(new java.awt.Color(255, 0, 102));
        p23.setText("Slobodno");
        getContentPane().add(p23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 219, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel49.setText("10:00 h");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        p24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p24.setForeground(new java.awt.Color(255, 0, 102));
        p24.setText("Slobodno");
        getContentPane().add(p24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 219, -1));

        p25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p25.setForeground(new java.awt.Color(255, 0, 102));
        p25.setText("Slobodno");
        getContentPane().add(p25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 219, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel50.setText("11:00 h");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setText("12:00 h");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        p16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p16.setForeground(new java.awt.Color(255, 0, 102));
        p16.setText("Slobodno");
        getContentPane().add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 219, -1));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setText("14:00 h");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, -1, -1));

        p17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p17.setForeground(new java.awt.Color(255, 0, 102));
        p17.setText("Slobodno");
        getContentPane().add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 219, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel40.setText("15:00 h");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, -1, -1));

        p18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p18.setForeground(new java.awt.Color(255, 0, 102));
        p18.setText("Slobodno");
        getContentPane().add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 550, 219, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setText("16:00 h");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 610, -1, -1));

        jLabel94.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel94.setText("13:00 h");
        getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 430, -1, -1));

        p60.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p60.setForeground(new java.awt.Color(255, 0, 102));
        p60.setText("Slobodno");
        getContentPane().add(p60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 430, 219, -1));

        jLabel95.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel95.setText("14:00 h");
        getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 490, -1, -1));

        p61.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p61.setForeground(new java.awt.Color(255, 0, 102));
        p61.setText("Slobodno");
        getContentPane().add(p61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 490, 219, -1));

        p26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p26.setForeground(new java.awt.Color(255, 0, 102));
        p26.setText("Slobodno");
        getContentPane().add(p26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 219, -1));

        p34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p34.setForeground(new java.awt.Color(255, 0, 102));
        p34.setText("Slobodno");
        getContentPane().add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 219, -1));

        jLabel63.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel63.setText("10:00 h");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        p35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p35.setForeground(new java.awt.Color(255, 0, 102));
        p35.setText("Slobodno");
        getContentPane().add(p35, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 219, -1));

        p36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p36.setForeground(new java.awt.Color(255, 0, 102));
        p36.setText("Slobodno");
        getContentPane().add(p36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 219, -1));

        jLabel64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel64.setText("11:00 h");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jLabel65.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel65.setText("12:00 h");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        p37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p37.setForeground(new java.awt.Color(255, 0, 102));
        p37.setText("Slobodno");
        getContentPane().add(p37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 219, -1));

        jLabel66.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel66.setText("13:00 h");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        p38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p38.setForeground(new java.awt.Color(255, 0, 102));
        p38.setText("Slobodno");
        getContentPane().add(p38, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 219, -1));

        jLabel96.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel96.setText("15:00 h");
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 550, -1, -1));

        p62.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p62.setForeground(new java.awt.Color(255, 0, 102));
        p62.setText("Slobodno");
        getContentPane().add(p62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 550, 219, -1));

        jLabel97.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel97.setText("16:00 h");
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 610, -1, -1));

        p63.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p63.setForeground(new java.awt.Color(255, 0, 102));
        p63.setText("Slobodno");
        getContentPane().add(p63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 610, 219, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setText("13:00 h");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        jLabel98.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel98.setText("17:00 h");
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 670, -1, -1));

        p27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p27.setForeground(new java.awt.Color(255, 0, 102));
        p27.setText("Slobodno");
        getContentPane().add(p27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 219, -1));

        p64.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p64.setForeground(new java.awt.Color(255, 0, 102));
        p64.setText("Slobodno");
        getContentPane().add(p64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 670, 219, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel53.setText("14:00 h");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        p28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p28.setForeground(new java.awt.Color(255, 0, 102));
        p28.setText("Slobodno");
        getContentPane().add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 219, -1));

        jLabel67.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel67.setText("14:00 h");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        p39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p39.setForeground(new java.awt.Color(255, 0, 102));
        p39.setText("Slobodno");
        getContentPane().add(p39, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 219, -1));

        jLabel68.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel68.setText("15:00 h");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));

        p40.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p40.setForeground(new java.awt.Color(255, 0, 102));
        p40.setText("Slobodno");
        getContentPane().add(p40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 219, -1));

        jLabel69.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel69.setText("16:00 h");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, -1, -1));

        p41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p41.setForeground(new java.awt.Color(255, 0, 102));
        p41.setText("Slobodno");
        getContentPane().add(p41, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, 219, -1));

        jLabel70.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel70.setText("17:00 h");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, -1, -1));

        p42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p42.setForeground(new java.awt.Color(255, 0, 102));
        p42.setText("Slobodno");
        getContentPane().add(p42, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, 219, -1));

        jLabel71.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel71.setText("18:00 h");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 730, -1, -1));

        p1o3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o3.setForeground(new java.awt.Color(255, 0, 102));
        p1o3.setText("Slobodno");
        getContentPane().add(p1o3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 219, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel54.setText("15:00 h");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        p29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p29.setForeground(new java.awt.Color(255, 0, 102));
        p29.setText("Slobodno");
        getContentPane().add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 219, -1));

        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setText("16:00 h");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        p19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p19.setForeground(new java.awt.Color(255, 0, 102));
        p19.setText("Slobodno");
        getContentPane().add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 219, -1));

        p30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p30.setForeground(new java.awt.Color(255, 0, 102));
        p30.setText("Slobodno");
        getContentPane().add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 219, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel42.setText("17:00 h");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 670, -1, -1));

        jLabel56.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel56.setText("17:00 h");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, -1, -1));

        p20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p20.setForeground(new java.awt.Color(255, 0, 102));
        p20.setText("Slobodno");
        getContentPane().add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, 219, -1));

        p31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p31.setForeground(new java.awt.Color(255, 0, 102));
        p31.setText("Slobodno");
        getContentPane().add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 219, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setText("18:00 h");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 730, -1, -1));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel72.setText("19:00 h");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 790, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel10.setText("Ponedjeljak");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("09:00 h");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("10:00 h");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("11:00 h");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("12:00 h");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("13:00 h");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        p43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p43.setForeground(new java.awt.Color(255, 0, 102));
        p43.setText("Slobodno");
        getContentPane().add(p43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 790, 219, -1));

        jLabel73.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel73.setText("20:00 h");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 850, -1, -1));

        p44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p44.setForeground(new java.awt.Color(255, 0, 102));
        p44.setText("Slobodno");
        getContentPane().add(p44, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 850, 219, -1));

        p1o1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o1.setForeground(new java.awt.Color(255, 0, 102));
        p1o1.setText("Slobodno");
        getContentPane().add(p1o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 730, 219, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setText("19:00 h");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 790, -1, -1));

        p21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p21.setForeground(new java.awt.Color(255, 0, 102));
        p21.setText("Slobodno");
        getContentPane().add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 790, 219, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setText("20:00 h");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 850, -1, -1));

        jLabel74.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel74.setText("Petak");
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 70, -1, -1));

        jLabel75.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel75.setText("05.06.2019");
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 30, 120, -1));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel76.setText("09:00 h");
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 180, -1, -1));

        p45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p45.setForeground(new java.awt.Color(255, 0, 102));
        p45.setText("Slobodno");
        getContentPane().add(p45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 180, 219, -1));

        jLabel77.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel77.setText("10:00 h");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 240, -1, -1));

        p46.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p46.setForeground(new java.awt.Color(255, 0, 102));
        p46.setText("Slobodno");
        getContentPane().add(p46, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 240, 219, -1));

        jLabel78.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel78.setText("11:00 h");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("14:00 h");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("15:00 h");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("16:00 h");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("17:00 h");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("18:00 h");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setText("19:00 h");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setText("20:00 h");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 850, -1, -1));

        p1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 0, 102));
        p1.setText("Slobodno");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 219, -1));

        p2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 0, 102));
        p2.setText("Slobodno");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 219, -1));

        p3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 0, 102));
        p3.setText("Slobodno");
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 219, -1));

        p47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p47.setForeground(new java.awt.Color(255, 0, 102));
        p47.setText("Slobodno");
        getContentPane().add(p47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 300, 219, -1));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel79.setText("12:00 h");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 370, -1, -1));

        p48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p48.setForeground(new java.awt.Color(255, 0, 102));
        p48.setText("Slobodno");
        getContentPane().add(p48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 219, -1));

        p1o4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p1o4.setForeground(new java.awt.Color(255, 0, 102));
        p1o4.setText("Slobodno");
        getContentPane().add(p1o4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 730, 219, -1));

        jLabel86.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel86.setText("19:00 h");
        getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 790, -1, -1));

        p54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p54.setForeground(new java.awt.Color(255, 0, 102));
        p54.setText("Slobodno");
        getContentPane().add(p54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 790, 219, -1));

        jLabel87.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel87.setText("20:00 h");
        getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 850, -1, -1));

        p55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p55.setForeground(new java.awt.Color(255, 0, 102));
        p55.setText("Slobodno");
        getContentPane().add(p55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 850, 219, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 130, 220, 17));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("01.06.2019");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, -1));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel80.setText("13:00 h");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 430, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 13));

        p49.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p49.setForeground(new java.awt.Color(255, 0, 102));
        p49.setText("Slobodno");
        getContentPane().add(p49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 430, 219, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("04.06.2019");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 120, -1));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel81.setText("14:00 h");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 490, -1, -1));

        jLabel33.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel33.setText("Cetvrtak");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, -1, -1));

        p50.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p50.setForeground(new java.awt.Color(255, 0, 102));
        p50.setText("Slobodno");
        getContentPane().add(p50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 490, 219, -1));

        jLabel82.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel82.setText("15:00 h");
        getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 550, -1, -1));

        p51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p51.setForeground(new java.awt.Color(255, 0, 102));
        p51.setText("Slobodno");
        getContentPane().add(p51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 550, 219, -1));

        jLabel83.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel83.setText("16:00 h");
        getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 610, -1, -1));

        p4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        p4.setForeground(new java.awt.Color(255, 0, 102));
        p4.setText("Slobodno");
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 219, -1));

        jToggleButton1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton1.setText("Osvjezi");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 930, 110, -1));

        jToggleButton2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton2.setText("next");
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 930, 110, -1));

        jToggleButton3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jToggleButton3.setText("back");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 930, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       new P1().setVisible(true);
       new P2().hide();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p14;
    private javax.swing.JLabel p15;
    private javax.swing.JLabel p16;
    private javax.swing.JLabel p17;
    private javax.swing.JLabel p18;
    private javax.swing.JLabel p19;
    private javax.swing.JLabel p1o;
    private javax.swing.JLabel p1o1;
    private javax.swing.JLabel p1o2;
    private javax.swing.JLabel p1o3;
    private javax.swing.JLabel p1o4;
    private javax.swing.JLabel p1o5;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p20;
    private javax.swing.JLabel p21;
    private javax.swing.JLabel p22;
    private javax.swing.JLabel p23;
    private javax.swing.JLabel p24;
    private javax.swing.JLabel p25;
    private javax.swing.JLabel p26;
    private javax.swing.JLabel p27;
    private javax.swing.JLabel p28;
    private javax.swing.JLabel p29;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p30;
    private javax.swing.JLabel p31;
    private javax.swing.JLabel p32;
    private javax.swing.JLabel p33;
    private javax.swing.JLabel p34;
    private javax.swing.JLabel p35;
    private javax.swing.JLabel p36;
    private javax.swing.JLabel p37;
    private javax.swing.JLabel p38;
    private javax.swing.JLabel p39;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p40;
    private javax.swing.JLabel p41;
    private javax.swing.JLabel p42;
    private javax.swing.JLabel p43;
    private javax.swing.JLabel p44;
    private javax.swing.JLabel p45;
    private javax.swing.JLabel p46;
    private javax.swing.JLabel p47;
    private javax.swing.JLabel p48;
    private javax.swing.JLabel p49;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p50;
    private javax.swing.JLabel p51;
    private javax.swing.JLabel p52;
    private javax.swing.JLabel p53;
    private javax.swing.JLabel p54;
    private javax.swing.JLabel p55;
    private javax.swing.JLabel p56;
    private javax.swing.JLabel p57;
    private javax.swing.JLabel p58;
    private javax.swing.JLabel p59;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p60;
    private javax.swing.JLabel p61;
    private javax.swing.JLabel p62;
    private javax.swing.JLabel p63;
    private javax.swing.JLabel p64;
    private javax.swing.JLabel p65;
    private javax.swing.JLabel p66;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    // End of variables declaration//GEN-END:variables
}
